version: '2'

services:
  openldap:
    image: docker.io/bitnami/openldap:2.6
    container_name: openldap
    hostname: olle
    ports:
      - '1389:1389'
      - '1636:1636'
    environment:
      - BITNAMI_DEBUG=yes
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=admin
      - LDAP_ROOT=dc=example,dc=com
      - LDAP_GROUP=group01
      - LDAP_USERS=user01,user02
      - LDAP_PASSWORDS=password1,password2
      - LDAP_EXTRA_SCHEMAS=cosine,inetorgperson,nis,memberof
    volumes:
      - 'openldap_data:/bitnami/openldap'
      - './ldifs/memberof.ldif:/opt/bitnami/openldap/etc/schema/memberof.ldif'

volumes:
  openldap_data:
    driver: local
