REPOSITORY=gunnar.lab.tail-f.com:5000/tailx-sdk-baseimage
TAG=morty-1.2.1v4
NAME=morty-121v4
HOSTNAME=morty
PORTS=9080:8080
USER=tobbe
EXTRA_RUN_FLAGS="-p 9008:8008 -p 4008:4000 -v /home/tobbe/work/git:/home/tobbe/work/git"
